"""Shared constants and primitive types for the site renderer."""

from __future__ import annotations

from collections.abc import Mapping
from pathlib import Path
from typing import Final, Literal, NewType


Lang = Literal["en", "bn", "ar", "ur"]
PageId = Literal["index", "work", "project", "blog", "stats"]
HtmlFragment = NewType("HtmlFragment", str)

LANGS: Final[tuple[Lang, ...]] = ("en", "bn", "ar", "ur")
PAGE_IDS: Final[tuple[PageId, ...]] = ("index", "work", "project", "blog", "stats")
DEFAULT_ROOT: Final[Path] = Path(__file__).resolve().parent.parent.parent
DEFAULT_CONTENT_PATH: Final[Path] = DEFAULT_ROOT / "content" / "site-content.json"
CSS_SOURCE_RELATIVE_PATH: Final[str] = "assets/css/styles.source.css"
CSS_OUTPUT_RELATIVE_PATH: Final[str] = "assets/css/styles.css"
SITEMAP_OUTPUT_RELATIVE_PATH: Final[str] = "sitemap.xml"
MANIFEST_OUTPUT_RELATIVE_PATH: Final[str] = "site.webmanifest"
SERVICE_WORKER_OUTPUT_RELATIVE_PATH: Final[str] = "service-worker.js"
GENERATED_COMMENT: Final[str] = "<!-- Generated by src/main.py --render-site. -->"
BACK_TO_TOP_LABELS: Final[Mapping[Lang, str]] = {
    "en": "Back to top",
    "bn": "উপরে ফিরে যান",
    "ar": "العَودَةُ إلى الأَعلى",
    "ur": "اوپر واپس جائیں",
}
THEME_DARK_LABELS: Final[Mapping[Lang, str]] = {
    "en": "Switch to dark mode",
    "bn": "ডার্ক মোডে যান",
    "ar": "التَّحوُّلُ إلى الوَضعِ الدَّاكِن",
    "ur": "ڈارک موڈ پر جائیں",
}
THEME_LIGHT_LABELS: Final[Mapping[Lang, str]] = {
    "en": "Switch to light mode",
    "bn": "লাইট মোডে যান",
    "ar": "التَّحوُّلُ إلى الوَضعِ الفاتِح",
    "ur": "لائٹ موڈ پر جائیں",
}
SKIP_TO_MAIN_LABELS: Final[Mapping[Lang, str]] = {
    "en": "Skip to main content",
    "bn": "মূল অংশে যান",
    "ar": "تَخَطَّ إلى المُحتَوَى الرَّئيسِي",
    "ur": "مرکزی مواد پر جائیں",
}
OG_LOCALE_BY_LANG: Final[Mapping[Lang, str]] = {
    "en": "en_US",
    "bn": "bn_BD",
    "ar": "ar_SA",
    "ur": "ur_PK",
}
SERVICE_WORKER_ASSET_PATHS: Final[tuple[str, ...]] = (
    "assets/css/styles.css",
    "assets/js/back-to-top.js",
    "assets/js/github-commits.js",
    "assets/js/goodreads-image-fallback.js",
    "assets/js/image-guard.js",
    "assets/js/language-switcher.js",
    "assets/js/service-worker-register.js",
    "assets/js/stats-snapshots.js",
    "assets/js/stats-theme-embeds.js",
    "assets/js/stats-utils.js",
    "assets/js/theme-toggle.js",
    "assets/js/umami-events.js",
    "assets/js/wakatime-charts.js",
    "assets/js/year.js",
    "assets/fonts/eb-garamond/EBGaramond-wght.ttf",
    "assets/fonts/noto-nastaliq-urdu/NotoNastaliqUrdu-wght.ttf",
    "assets/fonts/noto-serif-bengali/NotoSerifBengali-wdth-wght.ttf",
    "assets/fonts/scheherazade-new/ScheherazadeNew-Bold.ttf",
    "assets/fonts/scheherazade-new/ScheherazadeNew-Regular.ttf",
    "assets/icons/android-chrome-192x192.png",
    "assets/icons/android-chrome-512x512.png",
    "assets/icons/apple-touch-icon.png",
    "assets/icons/favicon-16x16.png",
    "assets/icons/favicon-32x32.png",
    "assets/icons/favicon.ico",
    "assets/images/logo.svg",
    "assets/images/og-card.png",
    "site.webmanifest",
)
THEME_BOOTSTRAP_SCRIPT: Final[str] = (
    "(function(){"
    "var storageKey='person-portfolio-theme';"
    "var theme='light';"
    "try{"
    "var stored=window.localStorage.getItem(storageKey);"
    "if(stored==='light'||stored==='dark'){theme=stored;}"
    "}catch(_error){}"
    "document.documentElement.setAttribute('data-theme',theme);"
    "})();"
)
