#!/usr/bin/env python3
"""Render the static portfolio site from a single JSON content source.

This script keeps the published site Unix-friendly:

- Silent success by default.
- Non-zero exit codes on schema or render failures.
- `--check` prints only stale output paths to stdout and exits 1 when any file
  is out of date.
- Diagnostics go to stderr.
- `--content -` reads JSON from stdin, which makes the tool composable in
  pipelines.

The renderer is intentionally strict. It parses JSON into typed, immutable
dataclasses first and only renders after the schema is validated.

The output side follows a small build-pipeline model:

- HTML pages are rendered from structured JSON and then minified.
- CSS is authored in `assets/css/styles.source.css` and emitted as minified
  `assets/css/styles.css`.
"""

from __future__ import annotations

import argparse
import datetime
import html
import json
import posixpath
import re
import subprocess
import sys
from urllib.parse import parse_qsl, urlencode, urlsplit, urlunsplit
from collections.abc import Iterable, Mapping, Sequence
from dataclasses import dataclass
from pathlib import Path
from typing import Callable, Final, Generic, Literal, NewType, TextIO, TypeVar, cast


Lang = Literal["en", "bn", "ar", "ur"]
PageId = Literal["index", "work", "project", "blog", "stats"]
HtmlFragment = NewType("HtmlFragment", str)

LANGS: Final[tuple[Lang, ...]] = ("en", "bn", "ar", "ur")
PAGE_IDS: Final[tuple[PageId, ...]] = ("index", "work", "project", "blog", "stats")
DEFAULT_ROOT: Final[Path] = Path(__file__).resolve().parent.parent
DEFAULT_CONTENT_PATH: Final[Path] = DEFAULT_ROOT / "content" / "site-content.json"
CSS_SOURCE_RELATIVE_PATH: Final[str] = "assets/css/styles.source.css"
CSS_OUTPUT_RELATIVE_PATH: Final[str] = "assets/css/styles.css"
SITEMAP_OUTPUT_RELATIVE_PATH: Final[str] = "sitemap.xml"
MANIFEST_OUTPUT_RELATIVE_PATH: Final[str] = "site.webmanifest"
EB_GARAMOND_WOFF2_TOKEN: Final[str] = "__EB_GARAMOND_WOFF2__"
GENERATED_COMMENT: Final[str] = "<!-- Generated by scripts/render_site.py. -->"
BACK_TO_TOP_LABELS: Final[Mapping[Lang, str]] = {
    "en": "Back to top",
    "bn": "উপরে ফিরে যান",
    "ar": "العَودَةُ إلى الأَعلى",
    "ur": "اوپر واپس جائیں",
}
THEME_DARK_LABELS: Final[Mapping[Lang, str]] = {
    "en": "Switch to dark mode",
    "bn": "ডার্ক মোডে যান",
    "ar": "التَّحوُّلُ إلى الوَضعِ الدَّاكِن",
    "ur": "ڈارک موڈ پر جائیں",
}
THEME_LIGHT_LABELS: Final[Mapping[Lang, str]] = {
    "en": "Switch to light mode",
    "bn": "লাইট মোডে যান",
    "ar": "التَّحوُّلُ إلى الوَضعِ الفاتِح",
    "ur": "لائٹ موڈ پر جائیں",
}
THEME_BOOTSTRAP_SCRIPT: Final[str] = (
    "(function(){"
    "var storageKey='person-portfolio-theme';"
    "var cookiePrefix=storageKey+'=';"
    "var windowNamePrefix='person-portfolio-theme=';"
    "function readCookieTheme(){"
    "var cookies=document.cookie?document.cookie.split('; '):[];"
    "for(var index=0;index<cookies.length;index+=1){"
    "var entry=cookies[index];"
    "if(entry.indexOf(cookiePrefix)===0){"
    "var value=entry.slice(cookiePrefix.length);"
    "if(value==='light'||value==='dark'){return value;}"
    "}"
    "}"
    "return null;"
    "}"
    "function readWindowNameTheme(){"
    "if(window.name.indexOf(windowNamePrefix)!==0){return null;}"
    "var value=window.name.slice(windowNamePrefix.length);"
    "if(value==='light'||value==='dark'){return value;}"
    "return null;"
    "}"
    "var theme='light';"
    "var windowNameTheme=readWindowNameTheme();"
    "if(windowNameTheme!==null){theme=windowNameTheme;}"
    "var cookieTheme=readCookieTheme();"
    "if(cookieTheme!==null){theme=cookieTheme;}"
    "try{"
    "var stored=window.localStorage.getItem(storageKey);"
    "if(stored==='light'||stored==='dark'){theme=stored;}"
    "}catch(_error){}"
    "document.documentElement.setAttribute('data-theme',theme);"
    "})();"
)
INLINE_SCRIPT_PATHS: Final[frozenset[str]] = frozenset(
    {
        "assets/js/image-guard.js",
        "assets/js/theme-toggle.js",
        "assets/js/language-switcher.js",
        "assets/js/year.js",
        "assets/js/back-to-top.js",
    }
)

T = TypeVar("T")


class ContentSchemaError(ValueError):
    """Raised when the JSON content source does not match the expected schema."""


@dataclass(frozen=True, slots=True)
class MetaText:
    """SEO and social metadata for one rendered page."""

    title: str
    description: str
    keywords: str


@dataclass(frozen=True, slots=True)
class HeaderText:
    """Visible page header copy."""

    site_title: str
    tagline: str


@dataclass(frozen=True, slots=True)
class LocaleInfo:
    """Locale-level chrome settings shared across pages."""

    direction: str | None
    author: str
    language_switcher_label: str
    og_image_alt: str


@dataclass(frozen=True, slots=True)
class SiteSettings:
    """Global site settings independent from a single page."""

    base_url: str
    google_site_verification: str
    language_menu_labels: Mapping[Lang, str]
    locales: Mapping[Lang, LocaleInfo]


@dataclass(frozen=True, slots=True)
class ContentCard:
    """Reusable content card used by highlights, work entries, and project items."""

    title: str
    href: str | None
    meta: str | None
    paragraphs: tuple[HtmlFragment, ...]
    bullets: tuple[HtmlFragment, ...]


@dataclass(frozen=True, slots=True)
class ArticleLink:
    """A linked article teaser."""

    title: str
    href: str
    summary: str
    meta: str | None


@dataclass(frozen=True, slots=True)
class IndexSection:
    """A homepage section with optional paragraphs, cards, article teasers, or contacts."""

    title: str
    paragraphs: tuple[HtmlFragment, ...]
    highlights: tuple[ContentCard, ...]
    articles: tuple[ArticleLink, ...]
    contacts: tuple[HtmlFragment, ...]


@dataclass(frozen=True, slots=True)
class IndexPageLocale:
    """Localized homepage content."""

    meta: MetaText
    header: HeaderText
    summary_card: tuple[HtmlFragment, ...]
    sections: tuple[IndexSection, ...]
    footer_html: HtmlFragment


@dataclass(frozen=True, slots=True)
class WorkPageLocale:
    """Localized work page content."""

    meta: MetaText
    header: HeaderText
    summary: HtmlFragment
    section_title: str
    entries: tuple[ContentCard, ...]
    footer_html: HtmlFragment


@dataclass(frozen=True, slots=True)
class ProjectGroup:
    """A titled group of projects."""

    title: str
    items: tuple[ContentCard, ...]


@dataclass(frozen=True, slots=True)
class ProjectPageLocale:
    """Localized projects page content."""

    meta: MetaText
    header: HeaderText
    groups: tuple[ProjectGroup, ...]
    footer_html: HtmlFragment


@dataclass(frozen=True, slots=True)
class BlogEntry:
    """A single writing entry on the blog page."""

    title: str
    href: str
    meta: str
    summary: str


@dataclass(frozen=True, slots=True)
class BlogPageLocale:
    """English-only blog page content."""

    meta: MetaText
    header: HeaderText
    articles: tuple[BlogEntry, ...]
    footer_html: HtmlFragment


@dataclass(frozen=True, slots=True)
class WakaTimeSection:
    """Structured settings for the WakaTime widget section."""

    title: str
    status_text: str
    languages_url: str
    summary_url: str
    aria_label: str


@dataclass(frozen=True, slots=True)
class LanguagesSection:
    """Structured settings for the language usage section."""

    title: str
    intro: HtmlFragment
    wakatime_copy: HtmlFragment
    wakatime_profile_href: str
    wakatime_badge_src: str
    wakatime_badge_alt: str
    wakatime_embed_src: str
    wakatime_embed_alt: str
    github_copy: HtmlFragment
    github_profile_href: str
    github_embed_src: str
    github_embed_alt: str


@dataclass(frozen=True, slots=True)
class GitHubCommitsSection:
    """Structured settings for the GitHub contribution section."""

    title: str
    description: str
    status_text: str
    contrib_url: str
    source_label: str
    source_href: str
    source_text: str
    heatmap_aria_label: str
    legend_aria_label: str


@dataclass(frozen=True, slots=True)
class LeetCodeSection:
    """Structured settings for the LeetCode section."""

    title: str
    copy: HtmlFragment
    thanks: HtmlFragment
    card_src: str
    card_alt: str


@dataclass(frozen=True, slots=True)
class LearningPathSection:
    """Structured settings for the roadmap section."""

    title: str
    copy: HtmlFragment
    href: str
    image_src: str
    image_alt: str


@dataclass(frozen=True, slots=True)
class GoodreadsSection:
    """Structured settings for the Goodreads embed."""

    title: str
    copy: str
    widget_id: str
    profile_href: str
    script_src: str


@dataclass(frozen=True, slots=True)
class StatsSections:
    """All stats subsections grouped into one typed container."""

    wakatime: WakaTimeSection
    languages: LanguagesSection
    github_commits: GitHubCommitsSection
    leetcode: LeetCodeSection
    learning_path: LearningPathSection
    goodreads: GoodreadsSection


@dataclass(frozen=True, slots=True)
class StatsPageLocale:
    """English-only stats page content."""

    meta: MetaText
    header: HeaderText
    intro: tuple[HtmlFragment, ...]
    sections: StatsSections
    footer_html: HtmlFragment


@dataclass(frozen=True, slots=True)
class LocalizedPage(Generic[T]):
    """A page definition keyed by locale."""

    og_type: str
    locales: Mapping[Lang, T]


RouteMap = Mapping[Lang, str]
RouteTable = Mapping[PageId, RouteMap]
NavigationTable = Mapping[Lang, tuple[PageId, ...]]
NavigationLabels = Mapping[PageId, Mapping[Lang, str]]


@dataclass(frozen=True, slots=True)
class SiteContent:
    """Fully parsed and typed site content."""

    site: SiteSettings
    routes: RouteTable
    navigation: NavigationTable
    navigation_labels: NavigationLabels
    index_page: LocalizedPage[IndexPageLocale]
    work_page: LocalizedPage[WorkPageLocale]
    project_page: LocalizedPage[ProjectPageLocale]
    blog_page: LocalizedPage[BlogPageLocale]
    stats_page: LocalizedPage[StatsPageLocale]

    def iter_pages(
        self,
        page_filter: frozenset[PageId] | None = None,
        lang_filter: frozenset[Lang] | None = None,
    ) -> Iterable[tuple[PageId, Lang, str, str]]:
        """Yield page_id, lang, output path, and rendered HTML."""

        for page_id in PAGE_IDS:
            if page_filter is not None and page_id not in page_filter:
                continue
            localized_page = self.page_for(page_id)
            route_map = self.routes[page_id]
            for lang, route in route_map.items():
                if lang_filter is not None and lang not in lang_filter:
                    continue
                yield (
                    page_id,
                    lang,
                    route,
                    render_page(self, page_id, lang, route, localized_page.og_type),
                )

    def page_for(
        self,
        page_id: PageId,
    ) -> (
        LocalizedPage[IndexPageLocale]
        | LocalizedPage[WorkPageLocale]
        | LocalizedPage[ProjectPageLocale]
        | LocalizedPage[BlogPageLocale]
        | LocalizedPage[StatsPageLocale]
    ):
        """Return the typed page descriptor for a page id."""

        if page_id == "index":
            return self.index_page
        if page_id == "work":
            return self.work_page
        if page_id == "project":
            return self.project_page
        if page_id == "blog":
            return self.blog_page
        return self.stats_page


class CliArgs(argparse.Namespace):
    """Typed CLI arguments after argparse parsing."""

    content: str = str(DEFAULT_CONTENT_PATH)
    root: str = str(DEFAULT_ROOT)
    check: bool = False
    page: list[str] | None = None
    lang: list[str] | None = None
    verbose: bool = False


def require_mapping(value: object, path: str) -> Mapping[str, object]:
    """Return a JSON object after validating its runtime type."""

    if not isinstance(value, dict):
        raise ContentSchemaError(f"{path} must be an object")
    raw_mapping = cast(dict[object, object], value)
    if not all(isinstance(key, str) for key in raw_mapping):
        raise ContentSchemaError(f"{path} must be an object with string keys")
    return cast(dict[str, object], raw_mapping)


def require_sequence(value: object, path: str) -> Sequence[object]:
    """Return a JSON array after validating its runtime type."""

    if not isinstance(value, list):
        raise ContentSchemaError(f"{path} must be an array")
    return cast(list[object], value)


def require_string(value: object, path: str) -> str:
    """Return a string field after validating its runtime type."""

    if not isinstance(value, str):
        raise ContentSchemaError(f"{path} must be a string")
    return value


def require_html_fragment(value: object, path: str) -> HtmlFragment:
    """Return a trusted HTML fragment string from the content file."""

    return HtmlFragment(require_string(value, path))


def require_optional_string(value: object, path: str) -> str | None:
    """Return a string or None after runtime validation."""

    if value is None:
        return None
    return require_string(value, path)


def get_required(mapping: Mapping[str, object], key: str, path: str) -> object:
    """Fetch a required key or raise a schema error with a precise path."""

    if key not in mapping:
        raise ContentSchemaError(f"{path}.{key} is required")
    return mapping[key]


def get_optional(mapping: Mapping[str, object], key: str) -> object | None:
    """Fetch an optional key without forcing callers to repeat membership checks."""

    return mapping.get(key)


def parse_string_tuple(value: object, path: str) -> tuple[str, ...]:
    """Parse an array of plain strings."""

    return tuple(require_string(item, f"{path}[{index}]") for index, item in enumerate(require_sequence(value, path)))


def parse_html_tuple(value: object, path: str) -> tuple[HtmlFragment, ...]:
    """Parse an array of trusted HTML fragments."""

    return tuple(
        require_html_fragment(item, f"{path}[{index}]")
        for index, item in enumerate(require_sequence(value, path))
    )


def parse_lang(value: str, path: str) -> Lang:
    """Parse and validate a language code."""

    if value not in LANGS:
        raise ContentSchemaError(f"{path} must be one of {', '.join(LANGS)}")
    return value


def parse_page_id(value: str, path: str) -> PageId:
    """Parse and validate a page identifier."""

    if value not in PAGE_IDS:
        raise ContentSchemaError(f"{path} must be one of {', '.join(PAGE_IDS)}")
    return value


def parse_mapping_of_strings(
    value: object,
    path: str,
    *,
    key_parser: Callable[[str, str], T],
) -> dict[T, str]:
    """Parse a JSON object whose values must all be strings."""

    raw = require_mapping(value, path)
    parsed: dict[T, str] = {}
    for raw_key, raw_value in raw.items():
        parsed[key_parser(raw_key, f"{path}.{raw_key}")] = require_string(
            raw_value,
            f"{path}.{raw_key}",
        )
    return parsed


def parse_meta(value: object, path: str) -> MetaText:
    """Parse page metadata."""

    raw = require_mapping(value, path)
    return MetaText(
        title=require_string(get_required(raw, "title", path), f"{path}.title"),
        description=require_string(get_required(raw, "description", path), f"{path}.description"),
        keywords=require_string(get_required(raw, "keywords", path), f"{path}.keywords"),
    )


def parse_header(value: object, path: str) -> HeaderText:
    """Parse visible page header text."""

    raw = require_mapping(value, path)
    return HeaderText(
        site_title=require_string(get_required(raw, "site_title", path), f"{path}.site_title"),
        tagline=require_string(get_required(raw, "tagline", path), f"{path}.tagline"),
    )


def parse_locale_info(value: object, path: str) -> LocaleInfo:
    """Parse locale-wide settings used by all pages in one language."""

    raw = require_mapping(value, path)
    return LocaleInfo(
        direction=require_optional_string(get_optional(raw, "dir"), f"{path}.dir"),
        author=require_string(get_required(raw, "author", path), f"{path}.author"),
        language_switcher_label=require_string(
            get_required(raw, "language_switcher_label", path),
            f"{path}.language_switcher_label",
        ),
        og_image_alt=require_string(get_required(raw, "og_image_alt", path), f"{path}.og_image_alt"),
    )


def parse_site_settings(value: object, path: str) -> SiteSettings:
    """Parse the top-level site settings block."""

    raw = require_mapping(value, path)
    menu_labels = parse_mapping_of_strings(
        get_required(raw, "language_menu_labels", path),
        f"{path}.language_menu_labels",
        key_parser=parse_lang,
    )
    locales_raw = require_mapping(get_required(raw, "locales", path), f"{path}.locales")
    locales: dict[Lang, LocaleInfo] = {}
    for raw_lang, raw_locale in locales_raw.items():
        lang = parse_lang(raw_lang, f"{path}.locales.{raw_lang}")
        locales[lang] = parse_locale_info(raw_locale, f"{path}.locales.{raw_lang}")
    return SiteSettings(
        base_url=require_string(get_required(raw, "base_url", path), f"{path}.base_url"),
        google_site_verification=require_string(
            get_required(raw, "google_site_verification", path),
            f"{path}.google_site_verification",
        ),
        language_menu_labels=menu_labels,
        locales=locales,
    )


def parse_content_card(value: object, path: str) -> ContentCard:
    """Parse a reusable highlight/work/project card."""

    raw = require_mapping(value, path)
    paragraphs_value = get_optional(raw, "paragraphs")
    bullets_value = get_optional(raw, "bullets")
    href_value = get_optional(raw, "href")
    meta_value = get_optional(raw, "meta")
    return ContentCard(
        title=require_string(get_required(raw, "title", path), f"{path}.title"),
        href=require_optional_string(href_value, f"{path}.href"),
        meta=require_optional_string(meta_value, f"{path}.meta"),
        paragraphs=parse_html_tuple(paragraphs_value, f"{path}.paragraphs")
        if paragraphs_value is not None
        else (),
        bullets=parse_html_tuple(bullets_value, f"{path}.bullets") if bullets_value is not None else (),
    )


def parse_article_link(value: object, path: str) -> ArticleLink:
    """Parse a linked article teaser."""

    raw = require_mapping(value, path)
    return ArticleLink(
        title=require_string(get_required(raw, "title", path), f"{path}.title"),
        href=require_string(get_required(raw, "href", path), f"{path}.href"),
        summary=require_string(get_required(raw, "summary", path), f"{path}.summary"),
        meta=require_optional_string(get_optional(raw, "meta"), f"{path}.meta"),
    )


def parse_index_section(value: object, path: str) -> IndexSection:
    """Parse one homepage section."""

    raw = require_mapping(value, path)
    highlights_value = get_optional(raw, "highlights")
    articles_value = get_optional(raw, "articles")
    contacts_value = get_optional(raw, "contacts")
    paragraphs_value = get_optional(raw, "paragraphs")
    return IndexSection(
        title=require_string(get_required(raw, "title", path), f"{path}.title"),
        paragraphs=parse_html_tuple(paragraphs_value, f"{path}.paragraphs")
        if paragraphs_value is not None
        else (),
        highlights=tuple(
            parse_content_card(item, f"{path}.highlights[{index}]")
            for index, item in enumerate(require_sequence(highlights_value, f"{path}.highlights"))
        )
        if highlights_value is not None
        else (),
        articles=tuple(
            parse_article_link(item, f"{path}.articles[{index}]")
            for index, item in enumerate(require_sequence(articles_value, f"{path}.articles"))
        )
        if articles_value is not None
        else (),
        contacts=parse_html_tuple(contacts_value, f"{path}.contacts") if contacts_value is not None else (),
    )


def parse_index_page_locale(value: object, path: str) -> IndexPageLocale:
    """Parse localized homepage content."""

    raw = require_mapping(value, path)
    sections_value = require_sequence(get_required(raw, "sections", path), f"{path}.sections")
    return IndexPageLocale(
        meta=parse_meta(get_required(raw, "meta", path), f"{path}.meta"),
        header=parse_header(get_required(raw, "header", path), f"{path}.header"),
        summary_card=parse_html_tuple(get_required(raw, "summary_card", path), f"{path}.summary_card"),
        sections=tuple(
            parse_index_section(item, f"{path}.sections[{index}]")
            for index, item in enumerate(sections_value)
        ),
        footer_html=require_html_fragment(get_required(raw, "footer_html", path), f"{path}.footer_html"),
    )


def parse_work_page_locale(value: object, path: str) -> WorkPageLocale:
    """Parse localized work page content."""

    raw = require_mapping(value, path)
    entries_value = require_sequence(get_required(raw, "entries", path), f"{path}.entries")
    return WorkPageLocale(
        meta=parse_meta(get_required(raw, "meta", path), f"{path}.meta"),
        header=parse_header(get_required(raw, "header", path), f"{path}.header"),
        summary=require_html_fragment(get_required(raw, "summary", path), f"{path}.summary"),
        section_title=require_string(get_required(raw, "section_title", path), f"{path}.section_title"),
        entries=tuple(
            parse_content_card(item, f"{path}.entries[{index}]")
            for index, item in enumerate(entries_value)
        ),
        footer_html=require_html_fragment(get_required(raw, "footer_html", path), f"{path}.footer_html"),
    )


def parse_project_group(value: object, path: str) -> ProjectGroup:
    """Parse a projects page group."""

    raw = require_mapping(value, path)
    items_value = require_sequence(get_required(raw, "items", path), f"{path}.items")
    return ProjectGroup(
        title=require_string(get_required(raw, "title", path), f"{path}.title"),
        items=tuple(
            parse_content_card(item, f"{path}.items[{index}]")
            for index, item in enumerate(items_value)
        ),
    )


def parse_project_page_locale(value: object, path: str) -> ProjectPageLocale:
    """Parse localized projects page content."""

    raw = require_mapping(value, path)
    groups_value = require_sequence(get_required(raw, "groups", path), f"{path}.groups")
    return ProjectPageLocale(
        meta=parse_meta(get_required(raw, "meta", path), f"{path}.meta"),
        header=parse_header(get_required(raw, "header", path), f"{path}.header"),
        groups=tuple(
            parse_project_group(item, f"{path}.groups[{index}]")
            for index, item in enumerate(groups_value)
        ),
        footer_html=require_html_fragment(get_required(raw, "footer_html", path), f"{path}.footer_html"),
    )


def parse_blog_entry(value: object, path: str) -> BlogEntry:
    """Parse a blog entry."""

    raw = require_mapping(value, path)
    return BlogEntry(
        title=require_string(get_required(raw, "title", path), f"{path}.title"),
        href=require_string(get_required(raw, "href", path), f"{path}.href"),
        meta=require_string(get_required(raw, "meta", path), f"{path}.meta"),
        summary=require_string(get_required(raw, "summary", path), f"{path}.summary"),
    )


def parse_blog_page_locale(value: object, path: str) -> BlogPageLocale:
    """Parse blog page content."""

    raw = require_mapping(value, path)
    articles_value = require_sequence(get_required(raw, "articles", path), f"{path}.articles")
    return BlogPageLocale(
        meta=parse_meta(get_required(raw, "meta", path), f"{path}.meta"),
        header=parse_header(get_required(raw, "header", path), f"{path}.header"),
        articles=tuple(
            parse_blog_entry(item, f"{path}.articles[{index}]")
            for index, item in enumerate(articles_value)
        ),
        footer_html=require_html_fragment(get_required(raw, "footer_html", path), f"{path}.footer_html"),
    )


def parse_wakatime_section(value: object, path: str) -> WakaTimeSection:
    """Parse the WakaTime section settings."""

    raw = require_mapping(value, path)
    return WakaTimeSection(
        title=require_string(get_required(raw, "title", path), f"{path}.title"),
        status_text=require_string(get_required(raw, "status_text", path), f"{path}.status_text"),
        languages_url=require_string(get_required(raw, "languages_url", path), f"{path}.languages_url"),
        summary_url=require_string(get_required(raw, "summary_url", path), f"{path}.summary_url"),
        aria_label=require_string(get_required(raw, "aria_label", path), f"{path}.aria_label"),
    )


def parse_languages_section(value: object, path: str) -> LanguagesSection:
    """Parse the languages section settings."""

    raw = require_mapping(value, path)
    return LanguagesSection(
        title=require_string(get_required(raw, "title", path), f"{path}.title"),
        intro=require_html_fragment(get_required(raw, "intro", path), f"{path}.intro"),
        wakatime_copy=require_html_fragment(
            get_required(raw, "wakatime_copy", path),
            f"{path}.wakatime_copy",
        ),
        wakatime_profile_href=require_string(
            get_required(raw, "wakatime_profile_href", path),
            f"{path}.wakatime_profile_href",
        ),
        wakatime_badge_src=require_string(
            get_required(raw, "wakatime_badge_src", path),
            f"{path}.wakatime_badge_src",
        ),
        wakatime_badge_alt=require_string(
            get_required(raw, "wakatime_badge_alt", path),
            f"{path}.wakatime_badge_alt",
        ),
        wakatime_embed_src=require_string(
            get_required(raw, "wakatime_embed_src", path),
            f"{path}.wakatime_embed_src",
        ),
        wakatime_embed_alt=require_string(
            get_required(raw, "wakatime_embed_alt", path),
            f"{path}.wakatime_embed_alt",
        ),
        github_copy=require_html_fragment(get_required(raw, "github_copy", path), f"{path}.github_copy"),
        github_profile_href=require_string(
            get_required(raw, "github_profile_href", path),
            f"{path}.github_profile_href",
        ),
        github_embed_src=require_string(
            get_required(raw, "github_embed_src", path),
            f"{path}.github_embed_src",
        ),
        github_embed_alt=require_string(
            get_required(raw, "github_embed_alt", path),
            f"{path}.github_embed_alt",
        ),
    )


def parse_github_commits_section(value: object, path: str) -> GitHubCommitsSection:
    """Parse the GitHub contribution section settings."""

    raw = require_mapping(value, path)
    return GitHubCommitsSection(
        title=require_string(get_required(raw, "title", path), f"{path}.title"),
        description=require_string(get_required(raw, "description", path), f"{path}.description"),
        status_text=require_string(get_required(raw, "status_text", path), f"{path}.status_text"),
        contrib_url=require_string(get_required(raw, "contrib_url", path), f"{path}.contrib_url"),
        source_label=require_string(get_required(raw, "source_label", path), f"{path}.source_label"),
        source_href=require_string(get_required(raw, "source_href", path), f"{path}.source_href"),
        source_text=require_string(get_required(raw, "source_text", path), f"{path}.source_text"),
        heatmap_aria_label=require_string(
            get_required(raw, "heatmap_aria_label", path),
            f"{path}.heatmap_aria_label",
        ),
        legend_aria_label=require_string(
            get_required(raw, "legend_aria_label", path),
            f"{path}.legend_aria_label",
        ),
    )


def parse_leetcode_section(value: object, path: str) -> LeetCodeSection:
    """Parse the LeetCode section settings."""

    raw = require_mapping(value, path)
    return LeetCodeSection(
        title=require_string(get_required(raw, "title", path), f"{path}.title"),
        copy=require_html_fragment(get_required(raw, "copy", path), f"{path}.copy"),
        thanks=require_html_fragment(get_required(raw, "thanks", path), f"{path}.thanks"),
        card_src=require_string(get_required(raw, "card_src", path), f"{path}.card_src"),
        card_alt=require_string(get_required(raw, "card_alt", path), f"{path}.card_alt"),
    )


def parse_learning_path_section(value: object, path: str) -> LearningPathSection:
    """Parse the learning path section settings."""

    raw = require_mapping(value, path)
    return LearningPathSection(
        title=require_string(get_required(raw, "title", path), f"{path}.title"),
        copy=require_html_fragment(get_required(raw, "copy", path), f"{path}.copy"),
        href=require_string(get_required(raw, "href", path), f"{path}.href"),
        image_src=require_string(get_required(raw, "image_src", path), f"{path}.image_src"),
        image_alt=require_string(get_required(raw, "image_alt", path), f"{path}.image_alt"),
    )


def parse_goodreads_section(value: object, path: str) -> GoodreadsSection:
    """Parse the Goodreads section settings."""

    raw = require_mapping(value, path)
    return GoodreadsSection(
        title=require_string(get_required(raw, "title", path), f"{path}.title"),
        copy=require_string(get_required(raw, "copy", path), f"{path}.copy"),
        widget_id=require_string(get_required(raw, "widget_id", path), f"{path}.widget_id"),
        profile_href=require_string(get_required(raw, "profile_href", path), f"{path}.profile_href"),
        script_src=require_string(get_required(raw, "script_src", path), f"{path}.script_src"),
    )


def parse_stats_page_locale(value: object, path: str) -> StatsPageLocale:
    """Parse stats page content."""

    raw = require_mapping(value, path)
    sections = require_mapping(get_required(raw, "sections", path), f"{path}.sections")
    return StatsPageLocale(
        meta=parse_meta(get_required(raw, "meta", path), f"{path}.meta"),
        header=parse_header(get_required(raw, "header", path), f"{path}.header"),
        intro=parse_html_tuple(get_required(raw, "intro", path), f"{path}.intro"),
        sections=StatsSections(
            wakatime=parse_wakatime_section(
                get_required(sections, "wakatime", f"{path}.sections"),
                f"{path}.sections.wakatime",
            ),
            languages=parse_languages_section(
                get_required(sections, "languages", f"{path}.sections"),
                f"{path}.sections.languages",
            ),
            github_commits=parse_github_commits_section(
                get_required(sections, "github_commits", f"{path}.sections"),
                f"{path}.sections.github_commits",
            ),
            leetcode=parse_leetcode_section(
                get_required(sections, "leetcode", f"{path}.sections"),
                f"{path}.sections.leetcode",
            ),
            learning_path=parse_learning_path_section(
                get_required(sections, "learning_path", f"{path}.sections"),
                f"{path}.sections.learning_path",
            ),
            goodreads=parse_goodreads_section(
                get_required(sections, "goodreads", f"{path}.sections"),
                f"{path}.sections.goodreads",
            ),
        ),
        footer_html=require_html_fragment(get_required(raw, "footer_html", path), f"{path}.footer_html"),
    )


def parse_localized_page(
    value: object,
    path: str,
    *,
    locale_parser: Callable[[object, str], T],
) -> LocalizedPage[T]:
    """Parse a page container that holds one og:type and several localized variants."""

    raw = require_mapping(value, path)
    locales_raw = require_mapping(get_required(raw, "locales", path), f"{path}.locales")
    locales: dict[Lang, T] = {}
    for raw_lang, raw_locale in locales_raw.items():
        lang = parse_lang(raw_lang, f"{path}.locales.{raw_lang}")
        locales[lang] = locale_parser(raw_locale, f"{path}.locales.{raw_lang}")
    return LocalizedPage(
        og_type=require_string(get_required(raw, "og_type", path), f"{path}.og_type"),
        locales=locales,
    )


def parse_routes(value: object, path: str) -> dict[PageId, dict[Lang, str]]:
    """Parse route definitions for each page and locale."""

    raw = require_mapping(value, path)
    routes: dict[PageId, dict[Lang, str]] = {}
    for raw_page_id, raw_route_map in raw.items():
        page_id = parse_page_id(raw_page_id, f"{path}.{raw_page_id}")
        route_map_raw = require_mapping(raw_route_map, f"{path}.{raw_page_id}")
        route_map: dict[Lang, str] = {}
        for raw_lang, raw_route in route_map_raw.items():
            lang = parse_lang(raw_lang, f"{path}.{raw_page_id}.{raw_lang}")
            route_map[lang] = require_string(raw_route, f"{path}.{raw_page_id}.{raw_lang}")
        routes[page_id] = route_map
    return routes


def parse_navigation(value: object, path: str) -> dict[Lang, tuple[PageId, ...]]:
    """Parse per-locale navigation order."""

    raw = require_mapping(value, path)
    navigation: dict[Lang, tuple[PageId, ...]] = {}
    for raw_lang, raw_items in raw.items():
        lang = parse_lang(raw_lang, f"{path}.{raw_lang}")
        navigation[lang] = tuple(
            parse_page_id(item, f"{path}.{raw_lang}[{index}]")
            for index, item in enumerate(parse_string_tuple(raw_items, f"{path}.{raw_lang}"))
        )
    return navigation


def parse_navigation_labels(value: object, path: str) -> dict[PageId, dict[Lang, str]]:
    """Parse labels for each nav item in each available language."""

    raw = require_mapping(value, path)
    labels: dict[PageId, dict[Lang, str]] = {}
    for raw_page_id, raw_label_map in raw.items():
        page_id = parse_page_id(raw_page_id, f"{path}.{raw_page_id}")
        labels[page_id] = parse_mapping_of_strings(
            raw_label_map,
            f"{path}.{raw_page_id}",
            key_parser=parse_lang,
        )
    return labels


def parse_content_source(raw_value: object) -> SiteContent:
    """Parse the full content source into immutable typed dataclasses."""

    raw = require_mapping(raw_value, "root")
    pages_raw = require_mapping(get_required(raw, "pages", "root"), "root.pages")
    return SiteContent(
        site=parse_site_settings(get_required(raw, "site", "root"), "root.site"),
        routes=parse_routes(get_required(raw, "routes", "root"), "root.routes"),
        navigation=parse_navigation(get_required(raw, "navigation", "root"), "root.navigation"),
        navigation_labels=parse_navigation_labels(
            get_required(raw, "navigation_labels", "root"),
            "root.navigation_labels",
        ),
        index_page=parse_localized_page(
            get_required(pages_raw, "index", "root.pages"),
            "root.pages.index",
            locale_parser=parse_index_page_locale,
        ),
        work_page=parse_localized_page(
            get_required(pages_raw, "work", "root.pages"),
            "root.pages.work",
            locale_parser=parse_work_page_locale,
        ),
        project_page=parse_localized_page(
            get_required(pages_raw, "project", "root.pages"),
            "root.pages.project",
            locale_parser=parse_project_page_locale,
        ),
        blog_page=parse_localized_page(
            get_required(pages_raw, "blog", "root.pages"),
            "root.pages.blog",
            locale_parser=parse_blog_page_locale,
        ),
        stats_page=parse_localized_page(
            get_required(pages_raw, "stats", "root.pages"),
            "root.pages.stats",
            locale_parser=parse_stats_page_locale,
        ),
    )


def read_content_stream(content_path: str, stdin: TextIO) -> str:
    """Read JSON from a file path or stdin when the path is '-'."""

    if content_path == "-":
        return stdin.read()
    return Path(content_path).read_text(encoding="utf-8")


def load_site_content(content_path: str, stdin: TextIO) -> SiteContent:
    """Load and validate the content source."""

    raw_text = read_content_stream(content_path, stdin)
    try:
        raw_value = cast(object, json.loads(raw_text))
    except json.JSONDecodeError as error:
        raise ContentSchemaError(f"invalid JSON: {error.msg} at line {error.lineno}, column {error.colno}") from error
    return parse_content_source(raw_value)


def strip_css_comments(source: str) -> str:
    """Remove block comments from CSS while preserving string literals.

    The implementation is intentionally conservative and only understands the
    CSS constructs used in this repository. It avoids regex-only comment
    stripping so quoted `/* ... */` sequences remain intact.
    """

    result: list[str] = []
    index = 0
    in_string = False
    string_delimiter = ""
    length = len(source)
    while index < length:
        current = source[index]
        next_char = source[index + 1] if index + 1 < length else ""
        if in_string:
            result.append(current)
            if current == "\\" and index + 1 < length:
                result.append(source[index + 1])
                index += 2
                continue
            if current == string_delimiter:
                in_string = False
                string_delimiter = ""
            index += 1
            continue
        if current in ('"', "'"):
            in_string = True
            string_delimiter = current
            result.append(current)
            index += 1
            continue
        if current == "/" and next_char == "*":
            comment_end = source.find("*/", index + 2)
            if comment_end == -1:
                raise ContentSchemaError("assets/css/styles.source.css contains an unterminated CSS comment")
            index = comment_end + 2
            continue
        result.append(current)
        index += 1
    return "".join(result)


def collapse_css_whitespace(source: str) -> str:
    """Collapse runs of CSS whitespace outside string literals to one space."""

    result: list[str] = []
    in_string = False
    string_delimiter = ""
    pending_space = False
    index = 0
    length = len(source)
    while index < length:
        current = source[index]
        if in_string:
            if pending_space:
                result.append(" ")
                pending_space = False
            result.append(current)
            if current == "\\" and index + 1 < length:
                result.append(source[index + 1])
                index += 2
                continue
            if current == string_delimiter:
                in_string = False
                string_delimiter = ""
            index += 1
            continue
        if current in ('"', "'"):
            if pending_space:
                result.append(" ")
                pending_space = False
            in_string = True
            string_delimiter = current
            result.append(current)
            index += 1
            continue
        if current.isspace():
            pending_space = True
            index += 1
            continue
        if pending_space and result:
            result.append(" ")
            pending_space = False
        result.append(current)
        index += 1
    return "".join(result).strip()


def minify_css(source: str) -> str:
    """Produce a compact CSS payload from the readable source stylesheet."""

    collapsed = collapse_css_whitespace(strip_css_comments(source))
    minified = re.sub(r"\s*([{}:;,])\s*", r"\1", collapsed)
    minified = re.sub(r"\)\s+\{", "){", minified)
    minified = re.sub(r"\s*>\s*", ">", minified)
    minified = re.sub(r";}", "}", minified)
    return minified.strip() + "\n"


def minify_html_document(document: str) -> str:
    """Minify generated HTML without altering text-node semantics.

    The renderer only strips whitespace between tags and removes the generated
    build comment. It does not rewrite text content, attribute values, or inline
    HTML fragments coming from the content source.
    """

    without_comment = document.replace(f"{GENERATED_COMMENT}\n", "")
    return re.sub(r">\s+<", "><", without_comment).strip() + "\n"


def relative_href(from_output: str, to_output: str) -> str:
    """Compute a POSIX relative URL between two output paths."""

    from_dir = posixpath.dirname(from_output) or "."
    return posixpath.relpath(to_output, start=from_dir)


def route_for(routes: RouteTable, page_id: PageId, lang: Lang) -> str:
    """Resolve a route for a given page and locale, falling back to localized home."""

    page_routes = routes[page_id]
    if lang in page_routes:
        return page_routes[lang]
    return routes["index"][lang]


def canonical_url(base_url: str, route: str, page_id: PageId, lang: Lang) -> str:
    """Build the canonical URL for a rendered page."""

    if page_id == "index" and lang == "en":
        return f"{base_url}/"
    return f"{base_url}/{route}"


def alternate_language_links(site: SiteSettings, routes: RouteTable, page_id: PageId) -> tuple[str, ...]:
    """Build alternate-language link tags for the actual page variants only."""

    page_routes = routes[page_id]
    alternate_links: list[str] = []

    for alternate_lang in LANGS:
        if alternate_lang not in page_routes:
            continue
        alternate_href = canonical_url(site.base_url, page_routes[alternate_lang], page_id, alternate_lang)
        alternate_links.append(
            f'  <link rel="alternate" hreflang="{alternate_lang}" href="{html.escape(alternate_href)}" />'
        )

    default_lang = "en" if "en" in page_routes else next(iter(page_routes.keys()))
    default_href = canonical_url(site.base_url, page_routes[default_lang], page_id, default_lang)
    alternate_links.append(
        f'  <link rel="alternate" hreflang="x-default" href="{html.escape(default_href)}" />'
    )

    return tuple(alternate_links)


def page_lang_attrs(locale: LocaleInfo, lang: Lang) -> str:
    """Render the html element language and direction attributes."""

    if locale.direction is None:
        return f'lang="{lang}"'
    return f'lang="{lang}" dir="{locale.direction}"'


def asset_href(current_output: str, asset_path: str) -> str:
    """Resolve a relative asset href from the current output path."""

    return relative_href(current_output, asset_path)


def git_output(root: Path, *args: str) -> str | None:
    """Return trimmed git command output, or None when unavailable."""

    try:
        completed = subprocess.run(
            ("git", *args),
            cwd=root,
            check=True,
            capture_output=True,
            text=True,
        )
    except (OSError, subprocess.CalledProcessError):
        return None
    return completed.stdout.strip() or None


def github_repo_slug(remote_url: str) -> str | None:
    """Extract owner/repo from a GitHub remote URL."""

    normalized = remote_url.removesuffix(".git")
    if normalized.startswith("https://github.com/"):
        return normalized.removeprefix("https://github.com/")
    if normalized.startswith("git@github.com:"):
        return normalized.removeprefix("git@github.com:")
    return None


def eb_garamond_woff2_url(root: Path) -> str:
    """Return a cache-friendly WOFF2 URL with a safe local fallback."""

    local_path = "../fonts/eb-garamond/EBGaramond-wght.woff2"
    remote_url = git_output(root, "config", "--get", "remote.origin.url")
    commit_hash = git_output(root, "rev-parse", "HEAD")
    if remote_url is None or commit_hash is None:
        return local_path

    repo_slug = github_repo_slug(remote_url)
    if repo_slug is None:
        return local_path

    return f"https://cdn.jsdelivr.net/gh/{repo_slug}@{commit_hash}/assets/fonts/eb-garamond/EBGaramond-wght.woff2"


def render_css_source(source: str, root: Path) -> str:
    """Resolve build-time CSS placeholders before minification."""

    return source.replace(EB_GARAMOND_WOFF2_TOKEN, eb_garamond_woff2_url(root))


def replace_query_params(url: str, replacements: Mapping[str, str]) -> str:
    """Return a URL with selected query parameters replaced."""

    parts = urlsplit(url)
    query_items = dict(parse_qsl(parts.query, keep_blank_values=True))
    query_items.update(replacements)
    return urlunsplit((parts.scheme, parts.netloc, parts.path, urlencode(query_items), parts.fragment))


def stats_embed_theme_sources(light_url: str, *, provider: Literal["leetcode", "roadmap"]) -> tuple[str, str]:
    """Return light and dark URLs for theme-aware remote stats embeds."""

    if provider == "leetcode":
        dark_colors = "#3F3A36,#D6D3D1,#F5F5F4,#A8A29E,#FB923C,#73AF6F,#FACC15,#FF5555,"
        dark_url = replace_query_params(
            light_url,
            {
                "theme": "dark",
                "colors": dark_colors,
            },
        )
        return (light_url, dark_url)

    dark_url = replace_query_params(light_url, {"variant": "dark"})
    return (light_url, dark_url)


def render_head(
    site: SiteSettings,
    routes: RouteTable,
    page_id: PageId,
    lang: Lang,
    route: str,
    current_output: str,
    meta: MetaText,
) -> str:
    """Render the document head."""

    locale = site.locales[lang]
    canonical = canonical_url(site.base_url, route, page_id, lang)
    alternate_links = alternate_language_links(site, routes, page_id)
    og_image = f"{site.base_url}/assets/images/logo.svg"
    stylesheet = asset_href(current_output, "assets/css/styles.css")
    favicon_32 = asset_href(current_output, "assets/icons/favicon-32x32.png")
    favicon_16 = asset_href(current_output, "assets/icons/favicon-16x16.png")
    favicon_ico = asset_href(current_output, "assets/icons/favicon.ico")
    apple_touch_icon = asset_href(current_output, "assets/icons/apple-touch-icon.png")
    manifest = asset_href(current_output, "site.webmanifest")
    og_type = "website" if page_id == "index" else "article"
    return "\n".join(
        (
            "<head>",
            '  <meta charset="UTF-8" />',
            '  <meta name="viewport" content="width=device-width, initial-scale=1" />',
            f"  <title>{html.escape(meta.title)}</title>",
            f'  <meta name="description" content="{html.escape(meta.description)}" />',
            f'  <meta name="keywords" content="{html.escape(meta.keywords)}" />',
            f'  <meta name="author" content="{html.escape(locale.author)}" />',
            '  <meta name="robots" content="index, follow" />',
            f'  <link rel="canonical" href="{html.escape(canonical)}" />',
            *alternate_links,
            f'  <meta property="og:type" content="{og_type}" />',
            f'  <meta property="og:site_name" content="{html.escape(locale.author)}" />',
            f'  <meta property="og:url" content="{html.escape(canonical)}" />',
            f'  <meta property="og:title" content="{html.escape(meta.title)}" />',
            f'  <meta property="og:description" content="{html.escape(meta.description)}" />',
            f'  <meta property="og:image" content="{html.escape(og_image)}" />',
            f'  <meta property="og:image:alt" content="{html.escape(locale.og_image_alt)}" />',
            '  <meta name="twitter:card" content="summary_large_image" />',
            f'  <meta name="twitter:title" content="{html.escape(meta.title)}" />',
            f'  <meta name="twitter:description" content="{html.escape(meta.description)}" />',
            f'  <meta name="twitter:image" content="{html.escape(og_image)}" />',
            f"  <script>{THEME_BOOTSTRAP_SCRIPT}</script>",
            f'  <link rel="preload" href="{html.escape(stylesheet)}" as="style" />',
            f'  <link rel="stylesheet" href="{html.escape(stylesheet)}" />',
            f'  <link rel="icon" type="image/png" sizes="32x32" href="{html.escape(favicon_32)}" />',
            f'  <link rel="icon" type="image/png" sizes="16x16" href="{html.escape(favicon_16)}" />',
            f'  <link rel="shortcut icon" href="{html.escape(favicon_ico)}" />',
            f'  <link rel="apple-touch-icon" sizes="180x180" href="{html.escape(apple_touch_icon)}" />',
            f'  <link rel="manifest" href="{html.escape(manifest)}" />',
            f'  <meta name="google-site-verification" content="{html.escape(site.google_site_verification)}" />',
            "</head>",
        )
    )


def render_language_switcher(
    site: SiteSettings,
    routes: RouteTable,
    page_id: PageId,
    lang: Lang,
    current_output: str,
) -> str:
    """Render the language switcher for the actual localized page variants."""

    page_routes = routes[page_id]
    available_languages: list[Lang] = [target_lang for target_lang in LANGS if target_lang in page_routes]
    if len(available_languages) <= 1:
        return ""

    switcher_label = site.locales[lang].language_switcher_label
    menu_id = f"language-menu-{page_id}-{lang}"
    lines = [
        '      <div class="language-switcher" data-language-switcher>',
        (
            f'        <button class="language-switcher-button" type="button" aria-label="{html.escape(switcher_label)}" '
            f'aria-controls="{html.escape(menu_id)}" aria-expanded="false" aria-haspopup="true" '
            f'title="{html.escape(switcher_label)}" data-language-switcher-button>'
            '<span aria-hidden="true" class="language-switcher-globe"></span>'
            "</button>"
        ),
        f'        <div class="language-menu" id="{html.escape(menu_id)}" hidden data-language-switcher-menu>',
    ]
    for target_lang in available_languages:
        label = site.language_menu_labels[target_lang]
        href = relative_href(current_output, page_routes[target_lang])
        current_attr = ' aria-current="page"' if target_lang == lang else ""
        lines.append(
            f'        <a href="{html.escape(href)}" lang="{target_lang}"{current_attr}>{html.escape(label)}</a>'
        )
    lines.extend(('        </div>', "      </div>"))
    return "\n".join(lines)


def render_theme_toggle(lang: Lang) -> str:
    """Render the explicit light/dark theme toggle."""

    dark_label = THEME_DARK_LABELS[lang]
    light_label = THEME_LIGHT_LABELS[lang]
    return (
        f'      <button class="theme-toggle" type="button" aria-label="{html.escape(dark_label)}" '
        f'title="{html.escape(dark_label)}" aria-pressed="false" data-theme-toggle '
        f'data-dark-label="{html.escape(dark_label)}" data-light-label="{html.escape(light_label)}">'
        '<span class="theme-toggle-icon" aria-hidden="true" data-theme-toggle-icon>☾</span>'
        "</button>"
    )


def render_header_controls(
    site: SiteSettings,
    routes: RouteTable,
    page_id: PageId,
    lang: Lang,
    current_output: str,
) -> str:
    """Render top-right lightweight controls for theme and language."""

    controls = ['      <div class="header-controls">', render_theme_toggle(lang)]
    language_switcher = render_language_switcher(site, routes, page_id, lang, current_output)
    if language_switcher:
        controls.append(language_switcher)
    controls.append("      </div>")
    return "\n".join(controls)


def render_nav(
    content: SiteContent,
    page_id: PageId,
    lang: Lang,
    current_output: str,
) -> str:
    """Render the top navigation for one locale."""

    lines = ["      <nav>"]
    for nav_page_id in content.navigation[lang]:
        label = content.navigation_labels[nav_page_id][lang]
        href = relative_href(current_output, route_for(content.routes, nav_page_id, lang))
        current_attr = ' aria-current="page"' if nav_page_id == page_id else ""
        lines.append(f'        <a href="{html.escape(href)}"{current_attr}>{html.escape(label)}</a>')
    lines.append("      </nav>")
    return "\n".join(lines)


def sitemap_priority(page_id: PageId, lang: Lang) -> str:
    """Return the sitemap priority for a rendered page."""

    if lang == "en":
        if page_id == "index":
            return "1.0"
        return "0.8"
    if lang == "bn":
        return "0.7"
    return "0.6"


def render_sitemap(content: SiteContent, lastmod: str) -> str:
    """Render the XML sitemap for all generated pages."""

    lines = ['<?xml version="1.0" encoding="UTF-8"?>', '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">']

    for page_id in PAGE_IDS:
        for lang, route in content.routes[page_id].items():
            lines.extend(
                (
                    "    <url>",
                    f"        <loc>{html.escape(canonical_url(content.site.base_url, route, page_id, lang))}</loc>",
                    f"        <lastmod>{lastmod}</lastmod>",
                    f"        <priority>{sitemap_priority(page_id, lang)}</priority>",
                    "    </url>",
                )
            )

    lines.append("</urlset>")
    return "\n".join(lines) + "\n"


def render_webmanifest() -> str:
    """Render the web app manifest with raster icons and SVG fallback."""

    manifest = {
        "name": "Naimul Kabir Portfolio",
        "short_name": "NaimulKabir",
        "icons": [
            {
                "src": "/assets/icons/android-chrome-192x192.png",
                "sizes": "192x192",
                "type": "image/png",
                "purpose": "any",
            },
            {
                "src": "/assets/icons/android-chrome-512x512.png",
                "sizes": "512x512",
                "type": "image/png",
                "purpose": "any",
            },
            {
                "src": "/assets/images/logo.svg",
                "sizes": "any",
                "type": "image/svg+xml",
                "purpose": "any",
            },
        ],
        "theme_color": "#2f261a",
        "background_color": "#f7f0e1",
        "display": "standalone",
    }
    return json.dumps(manifest, indent=4) + "\n"


def render_footer(footer_html: HtmlFragment) -> str:
    """Render the page footer."""

    return "\n".join(("    <footer>", f"      <p>{footer_html}</p>", "    </footer>"))


def inline_script_tag(script_path: str) -> str:
    """Inline a local script file into the generated HTML."""

    source_path = DEFAULT_ROOT / script_path
    script_source = source_path.read_text(encoding="utf-8")
    safe_source = script_source.replace("</script", "<\\/script")
    return f"  <script>{safe_source}</script>"


def render_scripts(page_id: PageId, current_output: str) -> str:
    """Render deferred script tags for a page."""

    default_scripts = (
        "assets/js/image-guard.js",
        "assets/js/theme-toggle.js",
        "assets/js/language-switcher.js",
        "assets/js/year.js",
    )
    long_page_scripts = (
        "assets/js/image-guard.js",
        "assets/js/back-to-top.js",
        "assets/js/theme-toggle.js",
        "assets/js/language-switcher.js",
        "assets/js/year.js",
    )
    stats_scripts = (
        "assets/js/image-guard.js",
        "assets/js/theme-toggle.js",
        "assets/js/stats-theme-embeds.js",
        "assets/js/language-switcher.js",
        "assets/js/stats-snapshots.js",
        "assets/js/stats-utils.js",
        "assets/js/wakatime-charts.js",
        "assets/js/github-commits.js",
        "assets/js/year.js",
    )
    if page_id == "stats":
        paths = stats_scripts
    elif page_id in ("work", "project"):
        paths = long_page_scripts
    else:
        paths = default_scripts
    rendered_scripts: list[str] = []
    for path in paths:
        if path in INLINE_SCRIPT_PATHS:
            rendered_scripts.append(inline_script_tag(path))
            continue
        rendered_scripts.append(f'  <script defer src="{html.escape(asset_href(current_output, path))}"></script>')
    return "\n".join(rendered_scripts)


def render_back_to_top_button(lang: Lang) -> str:
    """Render the lightweight back-to-top control for long pages."""

    label = BACK_TO_TOP_LABELS[lang]
    return "\n".join(
        (
            (
                '    <button class="back-to-top" type="button" data-back-to-top hidden '
                f'aria-label="{html.escape(label)}" title="{html.escape(label)}">'
            ),
            '      <span aria-hidden="true">↑</span>',
            "    </button>",
        )
    )


def render_content_card(card: ContentCard) -> str:
    """Render a reusable content card."""

    title_html = html.escape(card.title)
    if card.href is not None:
        title_html = (
            f'<a href="{html.escape(card.href)}" target="_blank" rel="noreferrer">{title_html}</a>'
        )
    lines = ['          <article class="highlight">', f"            <h3>{title_html}</h3>"]
    if card.meta is not None:
        lines.append(f"            <p class=\"meta\">{html.escape(card.meta)}</p>")
    for paragraph in card.paragraphs:
        lines.append(f"            <p>{paragraph}</p>")
    if card.bullets:
        lines.append("            <ul>")
        for bullet in card.bullets:
            lines.append(f"              <li>{bullet}</li>")
        lines.append("            </ul>")
    lines.append("          </article>")
    return "\n".join(lines)


def render_article_teaser(article: ArticleLink) -> str:
    """Render a linked article teaser card."""

    return "\n".join(
        (
            '          <li class="article-item">',
            f'            <a href="{html.escape(article.href)}" target="_blank" rel="noreferrer">',
            f"              <h3>{html.escape(article.title)}</h3>",
            f"              <p>{html.escape(article.summary)}</p>",
            "            </a>",
            "          </li>",
        )
    )


def render_index_main(page: IndexPageLocale) -> str:
    """Render homepage main content."""

    lines = ["    <main>", "      <section>", '        <div class="summary-card">']
    for paragraph in page.summary_card:
        lines.append(f"          <p>{paragraph}</p>")
    lines.extend(("        </div>", "      </section>"))
    for section in page.sections:
        lines.append("      <section>")
        lines.append(f"        <h2 class=\"section-title\">{html.escape(section.title)}</h2>")
        for paragraph in section.paragraphs:
            lines.append(f"        <p>{paragraph}</p>")
        if section.highlights:
            lines.append('        <div class="highlight-list">')
            for item in section.highlights:
                lines.append(render_content_card(item))
            lines.append("        </div>")
        if section.articles:
            lines.append('        <ul class="article-list">')
            for article in section.articles:
                lines.append(render_article_teaser(article))
            lines.append("        </ul>")
        for contact in section.contacts:
            lines.append(f"        <p>{contact}</p>")
        lines.append("      </section>")
    lines.append("    </main>")
    return "\n".join(lines)


def render_work_main(page: WorkPageLocale) -> str:
    """Render work page main content."""

    lines = [
        "    <main>",
        "      <section>",
        '        <div class="summary-card">',
        f"          <p>{page.summary}</p>",
        "        </div>",
        "      </section>",
        "      <section>",
        f"        <h2 class=\"section-title\">{html.escape(page.section_title)}</h2>",
        '        <div class="highlight-list">',
    ]
    for entry in page.entries:
        lines.append(render_content_card(entry))
    lines.extend(("        </div>", "      </section>", "    </main>"))
    return "\n".join(lines)


def render_project_main(page: ProjectPageLocale) -> str:
    """Render project page main content."""

    lines = ["    <main>"]
    for group in page.groups:
        lines.extend(
            (
                "      <section>",
                f"        <h2 class=\"section-title\">{html.escape(group.title)}</h2>",
                '        <div class="highlight-list">',
            )
        )
        for item in group.items:
            lines.append(render_content_card(item))
        lines.extend(("        </div>", "      </section>"))
    lines.append("    </main>")
    return "\n".join(lines)


def render_blog_main(page: BlogPageLocale) -> str:
    """Render blog page main content."""

    lines = ["    <main>", "      <section>"]
    for index, article in enumerate(page.articles):
        if index > 0:
            lines.append("        <hr />")
        lines.extend(
            (
                "        <article>",
                '          <h2 class="section-title">',
                (
                    f'            <a href="{html.escape(article.href)}" target="_blank" rel="noreferrer">'
                    f"{html.escape(article.title)}</a>"
                ),
                "          </h2>",
                f"          <p class=\"meta\">{html.escape(article.meta)}</p>",
                f"          <p>{html.escape(article.summary)}</p>",
                "        </article>",
            )
        )
    lines.extend(("      </section>", "    </main>"))
    return "\n".join(lines)


def render_stats_main(page: StatsPageLocale) -> str:
    """Render stats page main content."""

    stats = page.sections
    leetcode_light_src, leetcode_dark_src = stats_embed_theme_sources(
        stats.leetcode.card_src,
        provider="leetcode",
    )
    roadmap_light_src, roadmap_dark_src = stats_embed_theme_sources(
        stats.learning_path.image_src,
        provider="roadmap",
    )
    lines = ["    <main>", "      <section>"]
    for paragraph in page.intro:
        lines.append(f"        <p>{paragraph}</p>")
    lines.extend(
        (
            "      </section>",
            "      <section>",
            '        <div class="summary-card stats-card">',
            f"          <h2 class=\"section-title\">{html.escape(stats.wakatime.title)}</h2>",
            (
                '          <div class="wakatime-widget" data-wakatime-widget '
                f'data-wakatime-languages-url="{html.escape(stats.wakatime.languages_url)}" '
                f'data-wakatime-summary-url="{html.escape(stats.wakatime.summary_url)}">'
            ),
            f'            <p class="wakatime-status" data-role="status">{html.escape(stats.wakatime.status_text)}</p>',
            '            <div class="wakatime-visuals" data-role="visuals" hidden>',
            '              <div class="wakatime-summary" data-role="summary-cards"></div>',
            (
                '              <ol class="wakatime-bars" data-role="language-bars" '
                f'aria-label="{html.escape(stats.wakatime.aria_label)}"></ol>'
            ),
            "            </div>",
            "          </div>",
            "        </div>",
            "      </section>",
            "      <section>",
            '        <div class="summary-card stats-card">',
            f"          <h2 class=\"section-title\">{html.escape(stats.github_commits.title)}</h2>",
            f"          <p>{html.escape(stats.github_commits.description)}</p>",
            (
                '          <div class="github-commits-widget" data-github-commits-widget '
                f'data-github-contrib-url="{html.escape(stats.github_commits.contrib_url)}">'
            ),
            (
                f'            <p class="github-commits-status" data-role="status">'
                f"{html.escape(stats.github_commits.status_text)}</p>"
            ),
            '            <div class="github-commits-visuals" data-role="visuals" hidden>',
            '              <div class="github-commits-summary" data-role="summary-cards"></div>',
            '              <div class="github-heatmap-wrap">',
            '                <div class="github-heatmap-scroll">',
            (
                '                  <div class="github-heatmap" data-role="heatmap" '
                f'aria-label="{html.escape(stats.github_commits.heatmap_aria_label)}"></div>'
            ),
            "                </div>",
            (
                '                <div class="github-heatmap-legend" data-role="legend" '
                f'aria-label="{html.escape(stats.github_commits.legend_aria_label)}"></div>'
            ),
            "              </div>",
            "            </div>",
            "          </div>",
            (
                f'          <p class="meta">{html.escape(stats.github_commits.source_label)} '
                f'<a href="{html.escape(stats.github_commits.source_href)}" target="_blank" rel="noreferrer">'
                f"{html.escape(stats.github_commits.source_text)}</a></p>"
            ),
            "        </div>",
            "      </section>",
            "      <section>",
            '        <div class="summary-card stats-card">',
            f"          <h2 class=\"section-title\">{html.escape(stats.leetcode.title)}</h2>",
            f"          <p>{stats.leetcode.copy}</p>",
            f"          <p><sub>{stats.leetcode.thanks}</sub></p>",
            (
                f'          <img data-hide-section-on-error="true" class="stats-embed stats-embed--leetcode-card" '
                f'src="{html.escape(leetcode_light_src)}" '
                f'data-theme-light-src="{html.escape(leetcode_light_src)}" '
                f'data-theme-dark-src="{html.escape(leetcode_dark_src)}" '
                f'alt="{html.escape(stats.leetcode.card_alt)}" width="500" height="250" decoding="async" loading="lazy" />'
            ),
            "        </div>",
            "      </section>",
            "      <section>",
            '        <div class="summary-card stats-card">',
            f"          <h2 class=\"section-title\">{html.escape(stats.learning_path.title)}</h2>",
            f"          <p>{stats.learning_path.copy}</p>",
            "          <br />",
            (
                f'          <a href="{html.escape(stats.learning_path.href)}">'
                f'<img data-hide-section-on-error="true" class="stats-embed stats-embed--roadmap-card" '
                f'src="{html.escape(roadmap_light_src)}" '
                f'data-theme-light-src="{html.escape(roadmap_light_src)}" '
                f'data-theme-dark-src="{html.escape(roadmap_dark_src)}" '
                f'alt="{html.escape(stats.learning_path.image_alt)}" width="1130" height="380" decoding="async" loading="lazy" /></a>'
            ),
            "        </div>",
            "      </section>",
            "      <section>",
            '        <div class="summary-card stats-card">',
            f"          <h2 class=\"section-title\">{html.escape(stats.goodreads.title)}</h2>",
            f"          <p>{html.escape(stats.goodreads.copy)}</p>",
            f'          <div class="goodreads-widget" id="gr_grid_widget_{html.escape(stats.goodreads.widget_id)}"></div>',
            "        </div>",
            "      </section>",
            "    </main>",
        )
    )
    return "\n".join(lines)


def render_main_for_page(
    content: SiteContent,
    page_id: PageId,
    lang: Lang,
) -> str:
    """Dispatch to the correct page renderer using typed locale data."""

    if page_id == "index":
        return render_index_main(content.index_page.locales[lang])
    if page_id == "work":
        return render_work_main(content.work_page.locales[lang])
    if page_id == "project":
        return render_project_main(content.project_page.locales[lang])
    if page_id == "blog":
        return render_blog_main(content.blog_page.locales[lang])
    return render_stats_main(content.stats_page.locales[lang])


def meta_for_page(content: SiteContent, page_id: PageId, lang: Lang) -> MetaText:
    """Fetch typed page metadata."""

    if page_id == "index":
        return content.index_page.locales[lang].meta
    if page_id == "work":
        return content.work_page.locales[lang].meta
    if page_id == "project":
        return content.project_page.locales[lang].meta
    if page_id == "blog":
        return content.blog_page.locales[lang].meta
    return content.stats_page.locales[lang].meta


def header_for_page(content: SiteContent, page_id: PageId, lang: Lang) -> HeaderText:
    """Fetch typed header copy."""

    if page_id == "index":
        return content.index_page.locales[lang].header
    if page_id == "work":
        return content.work_page.locales[lang].header
    if page_id == "project":
        return content.project_page.locales[lang].header
    if page_id == "blog":
        return content.blog_page.locales[lang].header
    return content.stats_page.locales[lang].header


def footer_for_page(content: SiteContent, page_id: PageId, lang: Lang) -> HtmlFragment:
    """Fetch typed footer HTML."""

    if page_id == "index":
        return content.index_page.locales[lang].footer_html
    if page_id == "work":
        return content.work_page.locales[lang].footer_html
    if page_id == "project":
        return content.project_page.locales[lang].footer_html
    if page_id == "blog":
        return content.blog_page.locales[lang].footer_html
    return content.stats_page.locales[lang].footer_html


def render_hero(current_output: str) -> str:
    """Render the shared logo asset used as the hero illustration."""

    del current_output
    logo_svg = (DEFAULT_ROOT / "assets" / "images" / "logo.svg").read_text(encoding="utf-8").strip()
    inline_logo = logo_svg.replace(
        "<svg ",
        '<svg class="hero-illustration" aria-hidden="true" focusable="false" ',
        1,
    )
    return f"      {inline_logo}"


def render_page(content: SiteContent, page_id: PageId, lang: Lang, route: str, og_type: str) -> str:
    """Render one page to a full HTML document."""

    del og_type  # The og:type is derived from the page kind in render_head.
    locale = content.site.locales[lang]
    header = header_for_page(content, page_id, lang)
    head = render_head(content.site, content.routes, page_id, lang, route, route, meta_for_page(content, page_id, lang))
    body_lines = [
        "<body>",
        '  <div class="site">',
        '    <header id="top">',
        render_header_controls(content.site, content.routes, page_id, lang, route),
        render_hero(route),
        f"      <h1 class=\"site-title\">{html.escape(header.site_title)}</h1>",
        f"      <p class=\"tagline\">{html.escape(header.tagline)}</p>",
        render_nav(content, page_id, lang, route),
        "    </header>",
        render_main_for_page(content, page_id, lang),
        render_footer(footer_for_page(content, page_id, lang)),
        "  </div>",
        render_back_to_top_button(lang) if page_id in ("work", "project") else "",
        render_scripts(page_id, route),
    ]
    if page_id == "stats":
        goodreads = content.stats_page.locales[lang].sections.goodreads
        body_lines.append(
            f'  <script src="{html.escape(goodreads.script_src)}" type="text/javascript" charset="utf-8"></script>'
        )
    body_lines.append("</body>")
    body = "\n".join(body_lines)
    document = "\n".join(
        (
            "<!DOCTYPE html>",
            GENERATED_COMMENT,
            f"<html {page_lang_attrs(locale, lang)}>",
            "",
            head,
            "",
            body,
            "",
            "</html>",
            "",
        )
    )
    return minify_html_document(document)


def render_outputs(
    content: SiteContent,
    *,
    root: Path,
    page_filter: frozenset[PageId] | None,
    lang_filter: frozenset[Lang] | None,
) -> dict[str, str]:
    """Render selected HTML outputs plus the minified global stylesheet."""

    build_date = datetime.date.today().isoformat()
    outputs = {
        route: rendered
        for _, _, route, rendered in content.iter_pages(page_filter=page_filter, lang_filter=lang_filter)
    }
    css_source_path = root / CSS_SOURCE_RELATIVE_PATH
    css_source = css_source_path.read_text(encoding="utf-8")
    outputs[CSS_OUTPUT_RELATIVE_PATH] = minify_css(render_css_source(css_source, root))
    outputs[SITEMAP_OUTPUT_RELATIVE_PATH] = render_sitemap(content, build_date)
    outputs[MANIFEST_OUTPUT_RELATIVE_PATH] = render_webmanifest()
    return outputs


def write_outputs(root: Path, outputs: Mapping[str, str]) -> None:
    """Write rendered outputs to disk."""

    for relative_path, rendered in outputs.items():
        output_path = root / relative_path
        output_path.parent.mkdir(parents=True, exist_ok=True)
        _ = output_path.write_text(rendered, encoding="utf-8")


def stale_outputs(root: Path, outputs: Mapping[str, str]) -> tuple[str, ...]:
    """Return outputs whose on-disk contents differ from freshly rendered content."""

    stale: list[str] = []
    for relative_path, rendered in outputs.items():
        output_path = root / relative_path
        if not output_path.exists() or output_path.read_text(encoding="utf-8") != rendered:
            stale.append(relative_path)
    return tuple(stale)


def emit_error(message: str) -> None:
    """Write one diagnostic line to stderr."""

    print(message, file=sys.stderr)


def parse_cli_args(argv: Sequence[str] | None) -> CliArgs:
    """Build and parse CLI arguments."""

    parser = argparse.ArgumentParser(
        description="Render the portfolio site from content/site-content.json.",
    )
    _ = parser.add_argument(
        "--content",
        default=str(DEFAULT_CONTENT_PATH),
        help="JSON content file to read, or '-' to read from stdin.",
    )
    _ = parser.add_argument(
        "--root",
        default=str(DEFAULT_ROOT),
        help="Repository root where HTML outputs will be written.",
    )
    _ = parser.add_argument(
        "--check",
        action="store_true",
        help="Do not write files. Print stale output paths and exit 1 if any differ.",
    )
    _ = parser.add_argument(
        "--page",
        action="append",
        choices=PAGE_IDS,
        help="Render only the selected page id. Repeat to render multiple pages.",
    )
    _ = parser.add_argument(
        "--lang",
        action="append",
        choices=LANGS,
        help="Render only the selected language. Repeat to render multiple languages.",
    )
    _ = parser.add_argument(
        "--verbose",
        action="store_true",
        help="Print rendered output paths to stderr.",
    )
    return parser.parse_args(argv, namespace=CliArgs())


def freeze_pages(values: Sequence[str] | None) -> frozenset[PageId] | None:
    """Convert an optional CLI list into a typed frozen page set."""

    if values is None:
        return None
    return frozenset(parse_page_id(value, "--page") for value in values)


def freeze_langs(values: Sequence[str] | None) -> frozenset[Lang] | None:
    """Convert an optional CLI list into a typed frozen language set."""

    if values is None:
        return None
    return frozenset(parse_lang(value, "--lang") for value in values)


def run(argv: Sequence[str] | None = None, *, stdin: TextIO = sys.stdin) -> int:
    """Run the renderer and return a process exit status."""

    args = parse_cli_args(argv)
    root = Path(args.root).resolve()
    try:
        content = load_site_content(args.content, stdin)
    except (ContentSchemaError, OSError) as error:
        emit_error(f"render_site.py: {error}")
        return 2

    try:
        outputs = render_outputs(
            content,
            root=root,
            page_filter=freeze_pages(args.page),
            lang_filter=freeze_langs(args.lang),
        )
    except OSError as error:
        emit_error(f"render_site.py: failed to read build assets: {error}")
        return 2

    if args.check:
        stale = stale_outputs(root, outputs)
        for relative_path in stale:
            print(relative_path)
        return 1 if stale else 0

    try:
        write_outputs(root, outputs)
    except OSError as error:
        emit_error(f"render_site.py: failed to write outputs: {error}")
        return 3

    if args.verbose:
        for relative_path in sorted(outputs):
            emit_error(f"rendered {relative_path}")

    return 0


def main() -> int:
    """Entry point used by the shebang and direct Python execution."""

    return run()


if __name__ == "__main__":
    raise SystemExit(main())
